apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-randomquotes
resources:
- ../../base
images:
 - name: bobjwalker99/randomquotes-k8s
   newName: bobjwalker99/randomquotes-k8s
   newTag: "0.1.79.1"

patches:
 - target:
      kind: Ingress
      name: randomquotes-ingress-nginx
   path: randomquotes-ingress-nginx.yaml
