apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah prod"

images:
 - name: octopussamples/randomquotes-k8s
   newName: octopussamples/randomquotes-k8s
   newTag: "0.0.1"

patches:
 - target:
    kind: Ingress
    name: randomquotes-ingress-nginx
   path: randomquotes-ingress-nginx.yaml