apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="prod kustomize overlay"

images:
 - name: bobjwalker99/randomquotes-k8s
   newName: bobjwalker99/randomquotes-k8s
   newTag: "0.1.5"

patches:
 - target:
    kind: Ingress
    name: randomquotes-ingress-nginx
   path: randomquotes-ingress-nginx.yaml