---
apiVersion: v1
kind: Service
metadata:
  name: argocd-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 6801
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-cluster-ip-service
              port:
                number: 6801
