apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: random-quotes-secrets
  literals:
  - homepageDisplay=blah  

resources:
- randomquotes-deployment.yaml