apiVersion: v1
kind: Secret
metadata:
  name: random-quotes-secrets
type: Opaque
stringData:
  homepageDisplay: "blah"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomquotes-deployment  
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: randomquotes-web
  template:
    metadata:
      labels:
        component: randomquotes-web
    spec:
      containers:
        - name: randomquotes-web
          image: bobjwalker99/randomquotes-k8s:0.1.80.1
          imagePullPolicy: "Always"
          ports:
           - containerPort: 8080
             name: http-port
          env:
           - name: RANDOM_SECRET_PHRASE
             valueFrom:
               secretKeyRef:
                 name: random-quotes-secrets
                 key: homepageDisplay    
---
apiVersion: v1
kind: Service
metadata:
  name: randomquotes-app-cluster-ip-service  
spec:
  type: ClusterIP
  selector:
    component: randomquotes-web
  ports:
    - port: 6801
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: randomquotes-gateway-nginx  
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: randomquotes-gateway-route-nginx
spec:
  parentRefs:
  - name: randomquotes-gateway-nginx
  hostnames:
  - "randomquotes.local"  
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: randomquotes-app-cluster-ip-service
        port: 6801