apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base
secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="dev kustomize overlay"
images:
  - name: bobjwalker99/randomquotes-k8s
    newName: bobjwalker99/randomquotes-k8s
    newTag: "0.1.49-tagging.22"
patches:
  - target:
      kind: Ingress
      name: randomquotes-ingress-nginx
    path: randomquotes-ingress-nginx.yaml
