apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development-randomquotes
resources:
  - ../../base
images:
  - name: bobjwalker99/randomquotes-k8s
    newName: bobjwalker99/randomquotes-k8s
    newTag: "0.1.90-helm.5"
patches:
  - target:
      kind: HTTPRoute
      name: randomquotes-gateway-route-nginx
    path: randomquotes-ingress-nginx.yaml
