name: Build Container

on:
    push:
      branches: 
        - main
        - 'feature/**'        
      paths:
          - 'src/**'
          - '.github/**'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
      paths:
        - 'src/**'
        - '.github/**'
    workflow_dispatch:

jobs:
    build-and-push-application:
        runs-on: ubuntu-latest        
        strategy:
          matrix:
            dotnet-version: ['8.0.x']
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: '0'
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.14
              with:
                  versionSpec: 5.x
            - id: determine_version
              name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.14
              with:
                  additionalArguments: /overrideconfig mode=Mainline
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_PAT_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PAT }}
            - name: install buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                version: latest
            - name: build and push website container
              working-directory: src
              run: | 
                  docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -f "./RandomQuotes.Web/Dockerfile"  --build-arg APP_VERSION=${{ steps.determine_version.outputs.semVer }} --tag bobjwalker99/randomquotes-k8s:${{ steps.determine_version.outputs.semVer }} --tag bobjwalker99/randomquotes-k8s:latest .                 
            - name: update dev kustomize              
              uses: mikefarah/yq@master              
              with:
                cmd: yq -i '.images.[0].newTag = "${{ steps.determine_version.outputs.semVer }}"' 'k8s/overlays/dev/kustomization.yaml'
            - name: commit the kustomize change
              uses: devops-infra/action-commit-push@master
              with:
                github_token: "${{ secrets.GITHUB_TOKEN }}"
                commit_message: "Updating the dev Kustomize overlay to ${{ steps.determine_version.outputs.semVer }}"
            - name: update tag
              uses: richardsimko/update-tag@v1
              with:
                tag_name: dev-argo
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}