name: Build Container

on:
    push:
      branches: 
        - main
      paths:
          - 'src/**'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
      paths:
        - 'src/**'
    workflow_dispatch:

jobs:
    build-and-push-application:
        runs-on: ubuntu-latest        
        strategy:
          matrix:
            dotnet-version: ['8.0.x']
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: '0'
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.14
              with:
                  versionSpec: 5.x
            - id: determine_version
              name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.14
              with:
                  additionalArguments: /overrideconfig mode=Mainline
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_PAT_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PAT }}
            - name: build and push website container
              working-directory: src
              run: | 
                  docker build -f "./RandomQuotes.Web/Dockerfile" --tag octopussamples/randomquotes-k8s:${{ steps.determine_version.outputs.semVer }} --tag octopussamples/randomquotes-k8s:latest .                  
                  docker push octopussamples/randomquotes-k8s:${{ steps.determine_version.outputs.semVer }}                   
                  docker push octopussamples/randomquotes-k8s:latest  